// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolksbankTracker.Core.Data;

#nullable disable

namespace VolksbankTracker.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918155957_AddSavingsCategory")]
    partial class AddSavingsCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VolksbankTracker.Core.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSavings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#22c55e",
                            Icon = "💰",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Einkommen"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ef4444",
                            Icon = "🏠",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Miete"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#f97316",
                            Icon = "🛒",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Lebensmittel"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#3b82f6",
                            Icon = "🚗",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#8b5cf6",
                            Icon = "🛡️",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Versicherungen"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ec4899",
                            Icon = "🎮",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Freizeit"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#14b8a6",
                            Icon = "💊",
                            IsFallback = false,
                            IsSavings = false,
                            Name = "Gesundheit"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6b7280",
                            Icon = "📦",
                            IsFallback = true,
                            IsSavings = false,
                            Name = "Sonstiges"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#0ea5e9",
                            Icon = "🐷",
                            IsFallback = false,
                            IsSavings = true,
                            Name = "Sparen"
                        });
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.MerchantCategoryMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MatchKey")
                        .IsUnique();

                    b.ToTable("MerchantCategoryMaps");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionsNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditorIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.MerchantCategoryMap", b =>
                {
                    b.HasOne("VolksbankTracker.Core.Data.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Transaction", b =>
                {
                    b.HasOne("VolksbankTracker.Core.Data.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
