// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolksbankTracker.Core.Data;

#nullable disable

namespace VolksbankTracker.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("VolksbankTracker.Core.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#22c55e",
                            Icon = "💰",
                            Keywords = "",
                            Name = "Einkommen"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#ef4444",
                            Icon = "🏠",
                            Keywords = "",
                            Name = "Miete"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#f97316",
                            Icon = "🛒",
                            Keywords = "",
                            Name = "Lebensmittel"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#3b82f6",
                            Icon = "🚗",
                            Keywords = "",
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#8b5cf6",
                            Icon = "🛡️",
                            Keywords = "",
                            Name = "Versicherungen"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#ec4899",
                            Icon = "🎮",
                            Keywords = "",
                            Name = "Freizeit"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#14b8a6",
                            Icon = "💊",
                            Keywords = "",
                            Name = "Gesundheit"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6b7280",
                            Icon = "📦",
                            Keywords = "",
                            Name = "Sonstiges"
                        });
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransactionsNew")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditorIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorIban")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DebtorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Transaction", b =>
                {
                    b.HasOne("VolksbankTracker.Core.Data.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VolksbankTracker.Core.Data.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
